### PR TITLE
Update to 1.14

### PR DESCRIPTION
**Pull request by NicolasECP**
This PR updates the plugin to 1.14. It also updates the Java version to 16 as well as spigot and the maven compiler plugin.

### CODE REVIEW

**Comment by NicolasECP** [comment]
How does this look?

**Review by TylerS1066 — APPROVED** [review]
These look good, I'll throw them in a test before merging this.

**Review by TylerS1066 — CHANGES_REQUESTED** [review]
Tested this, and other than the java incompatibilities it works.


Due to spigot's stupidity, they have implemented a maximum java version support in 1.14 of java 13, meaning this does not work with java 16.  Please downgrade the version to 13 or lower (I'd prefer 11 since it is LTS).

**Comment by NicolasECP** [comment]
Requested changes made

**Comment by TylerS1066** [comment]
I was unable to get this to build locally, something with the maven compiler plugin.

I recommend downgrading it from 3.8.1 and pulling the CI update to this to double check if it can compile.

**Pull request closed without merging**
